[tox]
envlist = py{39,310,311,312,313}, lint

[testenv]
deps =
    -r{toxinidir}/dev_requirements.txt
commands =
    coverage run -m pytest {posargs} {toxinidir}/tests/
    coverage report

[testenv:lint]
deps = flake8
commands = flake8 --max-complexity 10 gearman tests --ignore=E221,E266,E501 --builtins=unicode

[testenv:compile-requirements]
deps = pip-tools
commands =
    pip-compile --output-file=dev_requirements.txt dev_requirements.in

[testenv:update-requirements]
deps = pip-tools
commands =
    pip-compile --upgrade --output-file=dev_requirements.txt dev_requirements.in
